In [1]:
import numpy as np

## Exercícios Práticos para os métodos de solução de Sistema de Equações Lineares

1. Considere os sistemas de equações apresentados em aula para cada método abordado. Utilize o código desenvolvido de cada método para resolver de forma numérica o respectivo problema.

### Eliminação de Gauss

In [2]:
def eliminacao_gauss(A, b):
    #n recebe o valor da ordem da matriz A
    n = A.shape[0]

    #utilizando a outra variavel para 
    # nao alterar o valor de b diretamente
    b_ = b.copy()

    # hstack empilha o vetor b em A
    # b.reshape(-1, 1) serve para transformar b em vetor coluna
    # para ser empilhado em A
    A = np.hstack((A, b.reshape(-1, 1)))

    for k in range(n - 1):
        #começa em k + 1 e vai ate n
        for i in range(k + 1, n):
            m = A[i, k] / A[k, k]
            for j in range(k, n + 1):
                A[i, j] = A[i, j] - m * A[k, j]
            b_[i] = b_[i] - m * b_[k]

    #pega somente os coeficientes de A
    A_coef = A[:, :n]

    x = (np.linalg.inv(A_coef) @ b_).T

    print(x)

### Decomposição LU

In [3]:
def decomposicao_LU(A, b):
    #n recebe a ordem da matriz
    n = A.shape[0]
    # criando a matriz u com o mesmo tamanho de A
    U = np.zeros((n, n)) 
    # criando a matrizz L como identidade do mesmo tamanho de A
    L = np.eye(n)

    for i in range(n):
        for j in range(i, n):
            soma = 0
            for k in range(i):
                soma += L[i, k] * U[k, j]
            U[i, j] = A[i, j] - soma
        for j in range(i + 1, n):
            soma = 0
            for k in range(i):
                soma += L[j, k] * U[k, i]
            L[j, i] = (A[j, i] - soma) / U[i, i]

    y = np.linalg.inv(L) @ b
    x = np.linalg.inv(U) @ y

    print(x)

### Decomposição de Cholesky

In [4]:
def decomposicao_cholesky(A, b):
    #n recebe o valor da ordem de A
    n = A.shape[0]
    # Criando a matriz G com o mesmo tamanho de A
    G = np.zeros((n, n))

    for i in range(n):
        for j in range(i + 1):
            if i == j:
                soma = 0
                for k in range(j):
                    soma += G[i, k] ** 2
                G[i, j] = np.sqrt(A[i, j] - soma)
            else:
                soma = 0
                for k in range(j):
                    soma += G[i, k] * G[j, k]
                G[i, j] = (A[i, j] - soma) / G[j, j]

    y = np.linalg.inv(G) @ b
    x = np.linalg.inv(G.T) @ y

    print(x)

2. Considere o seguinte sistema de equações lineares:

$$
\begin{cases}
4x + 12y - 16z = 1 \\
12x + 37y - 43z = 2 \\
-16x - 43y + 98z = 3
\end{cases}
$$

a) Verifique se este sistema satisfaz as condições para utilização dos métodos de Decomposição LU e Cholesky, explicando sua resposta.

In [5]:
def eh_valida_LU(A):
    n = A.shape[0]
    m = A.shape[1]

    #verifica se a matriz é quadrada
    if n != m:
        return False
    
    # verifica se alguma das submatrizes
    # de ordem 1 ate n-1 possuem det = 0,
    # quebrando uma das condicoes da LU
    for i in range(n - 1):
        if np.linalg.det(A[:i,:i]) == 0:
            return False
    
    return True

def eh_valida_Cholesky(A):
    #verificando se a matriz é quadrada
    n = A.shape[0]
    m = A.shape[1]

    if n != m:
        return False

    #verificando se a matriz é simétrica
    for i in range(n):
        for j in range(m):
            if A[i, j] != A[j, i]:
                return False
    
    #verificando se A é positiva defininda
    # se algum autovalor for <= 0 ela nao é positiva definida
    autovalores = np.linalg.eigvals(A)
    if not np.all(autovalores > 0):
        return False
    
    """
    pode ser feito da seguinte maneira também:
    verifica se todas as submatrizes tem det > 0
    for i in range(n - 1):
        if np.linalg.det(A[:i,:i]) <= 0:
            return False
    """

    return True

A = np.array([
    [4.0, 12.0, -16.0],
    [12.0, 37.0, -43.0],
    [-16.0, -43.0, 98.0]
])
b = np.array([1, 2, 3])

print(f"A matriz é válida para Decomposição LU? {eh_valida_LU(A)}")
print(f"A matriz é válida para Decomposição Cholesky? {eh_valida_Cholesky(A)}")

    

A matriz é válida para Decomposição LU? True
A matriz é válida para Decomposição Cholesky? True


O resultado dado pela função de verificar condições para a Decomposição LU é True. Com isso, sabemos que a matriz $A$ dada como entrada é quadrada (quantidade igual de linhas e colunas), e todas as submatrizes de $A_k$,  $k = 1, \dots, n-1$ possuem $\operatorname{det(A_{k}) \neq 0}$

O resultado dado pela função de verificar condições para a Decomposição Cholesky é True. Com isso confirma-se que a matriz é quadrada (quantidade igual de linhas e colunas), simétrica ($A = A^T$, ou todos os $a_{ij}$ iguais aos $a_{ji}$) e que é positiva definida (com todos os autovalores $\lambda_{A} > 0$)

b) Utilizando os scripts desenvolvidos, obtenha solução numérica para esse sistema de equações lineares pelos métodos de Eliminação de Gauss e pelos métodos de Decomposição LU e Cholesky se forem viáveis.

In [6]:
print("Solução utilizando a Eliminação de Gauss")
eliminacao_gauss(A, b)
print("\nSolução utilizando a Decomposição LU")
decomposicao_LU(A, b)
print("\nSolução utilizando a Decomposição Cholesky")
decomposicao_cholesky(A, b)

Solução utilizando a Eliminação de Gauss
[28.58333333 -7.66666667  1.33333333]

Solução utilizando a Decomposição LU
[28.58333333 -7.66666667  1.33333333]

Solução utilizando a Decomposição Cholesky
[28.58333333 -7.66666667  1.33333333]


Como foi visto anteriormente, a matriz $A$ satisfaz todas as condições para ambas as Decomposições. Então serão utilizados somente os algoritmos para encontrar a solução. É possível confirmar o resultado, já que as 3 soluções foram as mesmas nos três métodos.