## Eliminação de Gauss

In [103]:
import numpy as np

In [ ]:
import numpy as np

A = np.array([z
    [6.0, 2.0, -1.0],
    [2.0, 4.0, 1.0],
    [3.0, 2.0, 8.0]
])

b = np.array([
    [7.0],
    [7.0],
    [13.0]
])
n = A.shape[0]

# hstack empilha o vetor b (tem que ter reshape para ficar do mesmo formato da matriz)
A = np.hstack((A, c))

for k in range(n - 1):
    #começa em k + 1 e vai ate n
    for i in range(k + 1, n):
        m = A[i, k] / A[k, k]

        for j in range(k, n + 1):
            A[i, j] = A[i, j] - m * A[k, j]

        b[i] = b[i] - m * b[k]

#pega somente os coeficientes de A
A_coef = A[:, :n]

x = (np.linalg.inv(A_coef) @ b).T

print(x)

[[1. 1. 1.]]


## Decomposição LU

In [105]:
A = np.array([
    [5.0, 2.0, 1.0],
    [3.0, 1.0, 4.0],
    [1.0, 1.0, 3.0]
])
b = np.array([0.0, -7.0, -5.0])
n = A.shape[0]
U = np.zeros((n, n))
L = np.eye(n)

for i in range(n):

    for j in range(i, n):
        soma = 0

        for k in range(i):
            soma += L[i, k] * U[k, j]

        U[i, j] = A[i, j] - soma

    for j in range(i + 1, n):
        soma = 0

        for k in range(i):
            soma += L[j, k] * U[k, i]

        L[j, i] = (A[j, i] - soma) / U[i, i]

y = np.linalg.inv(L) @ b
x = np.linalg.inv(U) @ y

print(x)

[ 2.49373172e-15  1.00000000e+00 -2.00000000e+00]


## Decomposição de Cholesky

In [106]:
A = np.array([
    [4.0, 2.0, -4.0],
    [2.0, 10.0, 4.0],
    [-4.0, 4.0, 9.0]
])
b = np.array([0.0, 6.0, 5.0])
n = A.shape[0]
G = np.zeros((n, n))

for i in range(n):
    for j in range(i + 1):
        if i == j:
            soma = 0
            for k in range(j):
                soma += G[i, k] ** 2
            G[i, j] = np.sqrt(A[i, j] - soma)
        else:
            soma = 0
            for k in range(j):
                soma += G[i, k] * G[j, k]
            G[i, j] = (A[i, j] - soma) / G[j, j]

y = np.linalg.inv(G) @ b
x = np.linalg.inv(G.T) @ y

print(x)

[1. 0. 1.]
