## Tarefa prática para os métodos de solução de Sistema de Equações Lineares

In [30]:
import numpy as np

1. Considere o seguinte sistema de equações lineares:

$$
\begin{cases}
16x_1 + 4x_2 + 8x_3 + 4x_4 = 32 \\
4x_1 + 10x_2 + 8x_3 + 4x_4 = 26 \\
8x_1 + 8x_2 + 12x_3 + 10x_4 = 38 \\
4x_1 + 4x_2 + 10x_3 + 12x_4 = 30
\end{cases}
$$

a) Verifique se este sistema satisfaz as condições para utilização dos métodos de Decomposição LU e Cholesky, explicando sua resposta.

In [31]:
A = np.array([
    [16.0, 4.0, 8.0, 4.0],
    [4.0, 10.0, 8.0, 4.0],
    [8.0, 8.0, 12.0, 10.0],
    [4.0, 4.0, 10.0, 12.0]
])
b = np.array([32, 26, 38, 30])

def eh_valida_LU(A):
    n = A.shape[0]
    m = A.shape[1]

    #verifica se a matriz é quadrada
    if n != m:
        return False
    
    # verifica se alguma das submatrizes
    # de ordem 1 ate n-1 possuem det = 0,
    # quebrando uma das condicoes da LU, ou seja, se A é positiva definida
    for i in range(n - 1):
        if np.linalg.det(A[:i,:i]) == 0:
            return False
    
    return True

def eh_valida_Cholesky(A):
    #verificando se a matriz é quadrada
    n = A.shape[0]
    m = A.shape[1]

    if n != m:
        return False

    #verificando se a matriz é simétrica
    for i in range(n):
        for j in range(m):
            if A[i, j] != A[j, i]:
                return False
    
    #verificando se A é positiva defininda
    # se algum autovalor for <= 0 ela nao é positiva definida
    # pode ser feito assim como foi feito na verificação de LU
    autovalores = np.linalg.eigvals(A)
    if not np.all(autovalores > 0):
        return False

    return True

print(f"A matriz é válida para Decomposição LU? {eh_valida_LU(A)}")
print(f"A matriz é válida para Decomposição Cholesky? {eh_valida_Cholesky(A)}")
    

A matriz é válida para Decomposição LU? True
A matriz é válida para Decomposição Cholesky? True


A matriz satisfaz as condições para decomposição LU pois possui mesma quantidade de linhas e colunas (matriz quadrada) e todos os menores principais $A_k$ satisfazem $\operatorname{det}(A_k) > 0$, para $k = 1, 2,\dots , n$, ou seja, também é positiva definida.

A matriz também satisfaz as condições para decomposição Cholesky, ou seja, é quadrada (já confirmado na outra verificação), é positiva definda (dessa vez foi confirmado atrvés dos autovalores: é positiva definida quando todos os autovalores de A são maiores que 0) e é simétrica, verificando se todo $a_{ij} = a_{ji}$.

b) Utilizando os scripts desenvolvidos, obtenha solução numérica para esse sistema de equações lineares pelo método de Eliminação de Gauss e pelos métodos de Decomposição LU e Cholesky, se forem viáveis.

In [32]:
def eliminacao_gauss(A, b):
    #n recebe o valor da ordem da matriz A
    n = A.shape[0]

    #utilizando a outra variavel para 
    # nao alterar o valor de b diretamente
    b_ = b.copy()

    # hstack empilha o vetor b em A
    # b.reshape(-1, 1) serve para transformar b em vetor coluna
    # para ser empilhado em A
    A = np.hstack((A, b.reshape(-1, 1)))

    for k in range(n - 1):
        #começa em k + 1 e vai ate n
        for i in range(k + 1, n):
            m = A[i, k] / A[k, k]
            for j in range(k, n + 1):
                A[i, j] = A[i, j] - m * A[k, j]
            b_[i] = b_[i] - m * b_[k]

    #pega somente os coeficientes de A
    A_coef = A[:, :n]

    x = (np.linalg.inv(A_coef) @ b_).T

    print(x)

def decomposicao_LU(A, b):
    #n recebe a ordem da matriz
    n = A.shape[0]
    # criando a matriz u com o mesmo tamanho de A
    U = np.zeros((n, n)) 
    # criando a matrizz L como identidade do mesmo tamanho de A
    L = np.eye(n)

    for i in range(n):
        for j in range(i, n):
            soma = 0
            for k in range(i):
                soma += L[i, k] * U[k, j]
            U[i, j] = A[i, j] - soma
        for j in range(i + 1, n):
            soma = 0
            for k in range(i):
                soma += L[j, k] * U[k, i]
            L[j, i] = (A[j, i] - soma) / U[i, i]

    y = np.linalg.inv(L) @ b
    x = np.linalg.inv(U) @ y

    print(x)

def decomposicao_cholesky(A, b):
    #n recebe o valor da ordem de A
    n = A.shape[0]
    # Criando a matriz G com o mesmo tamanho de A
    G = np.zeros((n, n))

    for i in range(n):
        for j in range(i + 1):
            if i == j:
                soma = 0
                for k in range(j):
                    soma += G[i, k] ** 2
                G[i, j] = np.sqrt(A[i, j] - soma)
            else:
                soma = 0
                for k in range(j):
                    soma += G[i, k] * G[j, k]
                G[i, j] = (A[i, j] - soma) / G[j, j]

    y = np.linalg.inv(G) @ b
    x = np.linalg.inv(G.T) @ y

    print(x)

print("Solução utilizando a Eliminação de Gauss")
eliminacao_gauss(A, b)
print("\nSolução utilizando a Decomposição LU")
decomposicao_LU(A, b)
print("\nSolução utilizando a Decomposição Cholesky")
decomposicao_cholesky(A, b)

Solução utilizando a Eliminação de Gauss
[1. 1. 1. 1.]

Solução utilizando a Decomposição LU
[1. 1. 1. 1.]

Solução utilizando a Decomposição Cholesky
[1. 1. 1. 1.]


c) Se for possível resolver pelo método de Decomposição LU, apresente a matriz L e U obtidas pelo método.

In [33]:
def mostrar_LU(A):
    #n recebe a ordem da matriz
    n = A.shape[0]
    # criando a matriz u com o mesmo tamanho de A
    U = np.zeros((n, n)) 
    # criando a matrizz L como identidade do mesmo tamanho de A
    L = np.eye(n)

    for i in range(n):
        for j in range(i, n):
            soma = 0
            for k in range(i):
                soma += L[i, k] * U[k, j]
            U[i, j] = A[i, j] - soma
        for j in range(i + 1, n):
            soma = 0
            for k in range(i):
                soma += L[j, k] * U[k, i]
            L[j, i] = (A[j, i] - soma) / U[i, i]

    print(f"Matriz L:\n {L}")
    print(f"\nMatriz U:\n {U}")

mostrar_LU(A)

Matriz L:
 [[1.         0.         0.         0.        ]
 [0.25       1.         0.         0.        ]
 [0.5        0.66666667 1.         0.        ]
 [0.25       0.33333333 1.5        1.        ]]

Matriz U:
 [[16.  4.  8.  4.]
 [ 0.  9.  6.  3.]
 [ 0.  0.  4.  6.]
 [ 0.  0.  0.  1.]]


d) Se for possível resolver pelo método de Cholesky, apresente a matriz G obtida pelo método.

In [34]:
def mostrar_G(A):
    #n recebe o valor da ordem de A
    n = A.shape[0]
    # Criando a matriz G com o mesmo tamanho de A
    G = np.zeros((n, n))

    for i in range(n):
        for j in range(i + 1):
            if i == j:
                soma = 0
                for k in range(j):
                    soma += G[i, k] ** 2
                G[i, j] = np.sqrt(A[i, j] - soma)
            else:
                soma = 0
                for k in range(j):
                    soma += G[i, k] * G[j, k]
                G[i, j] = (A[i, j] - soma) / G[j, j]

    print(f"\nMatriz G:\n {G}")

mostrar_G(A)


Matriz G:
 [[4. 0. 0. 0.]
 [1. 3. 0. 0.]
 [2. 2. 2. 0.]
 [1. 1. 3. 1.]]
